name: papapa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^0.9.10
  video_player: ^0.10.9
  photo_view: ^0.10.2
  double_back_to_close_app: ^1.2.0
  webview_flutter: ^1.0.0
  
  
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - images/1.jpg
    - images/2.jpg
    - images/CL.png
    - images/web.png
    - images/python.png
    - images/1PM25/1/1PY.PNG
    - images/1PM25/1/2PY.PNG
    - images/1PM25/1/3PY.PNG
    - images/1PM25/1/API.PNG
    - images/1PM25/HTML/1 HTML.PNG
    - images/1PM25/HTML/2 HTML.PNG
    - images/1PM25/HTML/3 HTML.PNG
    - images/1PM25/HTML/4 HTML.PNG
    - images/1PM25/HTML/5.PNG
    - videoPR/1pm25.mp4
  

    - images/2Covid19/1/1 PY Covid19.PNG
    - images/2Covid19/1/2 PY Covid19.PNG
    - images/2Covid19/1/3 PY Covid19.PNG
    - images/2Covid19/1/API PY Covid19.PNG
    - images/2Covid19/HTML/1 HTML Covid19.PNG
    - images/2Covid19/HTML/2 HTML Covid19.PNG
    - images/2Covid19/HTML/3 HTML Covid19.PNG
    - images/2Covid19/HTML/4 HTML Covid19.PNG
    - images/2Covid19/HTML/5.PNG
    - videoPR/2covid.mp4


    - images/3Weather/1/1 PY.PNG
    - images/3Weather/1/2 PY.PNG
    - images/3Weather/1/3 PY.PNG
    - images/3Weather/1/API PY.PNG
    - images/3Weather/HTML/1 HTML.PNG
    - images/3Weather/HTML/2 HTML.PNG
    - images/3Weather/HTML/3 HTML.PNG
    - images/3Weather/HTML/4 HTML.PNG
    - images/3Weather/HTML/5.PNG
    - videoPR/3weather.mp4

    - images/Web Page/1/1 PY of import.PNG
    - images/Web Page/1/2 PY of if else.PNG
    - images/Web Page/1/3 PY of API weather.PNG
    - images/Web Page/1/4 PY of API API2.PNG
    - images/Web Page/1/5 PY of DATA weather.PNG
    - images/Web Page/1/6 PY of DATA covid19.PNG
    - images/Web Page/1/7 PY of DATA AirQ End.PNG
    - images/Web Page/HTML/1 HTML.PNG
    - images/Web Page/HTML/2 HTML.PNG
    - images/Web Page/HTML/3 HTML.PNG
    - images/Web Page/HTML/4 HTML.PNG
    - images/Web Page/HTML/5 HTML.PNG
    - images/Web Page/HTML/6 HTML.PNG
    - images/Web Page/HTML/7 HTML.PNG
    - images/Web Page/HTML/8 HTML.PNG
    - images/Web Page/HTML/9 HTML.PNG
    - images/Web Page/HTML/10 HTML.PNG
    - images/Web Page/HTML/HTML Run.PNG
    - videoPR/allwebpage.mp4
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

